/* ============================================================
   ZOU – DATA
   ============================================================ */

const EVENTS = [
  {
    id: 1,
    title:       'Soirée Vinyle – Le Volta',
    subtitle:    '21h – Le Volta, Rue de la raquette',
    venue:       'Le Volta – Paris 11ème',
    location:    'Paris 19ème',
    places:      80,
    remaining:   34,
    price:       12,
    priceLabel:  '12 €',
    xp:          80,
    tag:         "Aujourd'hui",
    badge:       'Partenaire ZOU',
    hours:       '21h – 2h',
    type:        'Bar/Live',
    img:         'images/vinyle_background.png',
    description: "Une soirée vinyle intimiste dans le 11ème. Le Volta programme des DJs locaux avec une sélection soul, funk et jazz. Ambiance chaleureuse, cocktails signature, vraie déco rétro.",
    warnMsg:     "Il te manque 1 sortie pour passer au Niveau 5 et gagner une pinte offerte au Volta.",
    progMsg:     "Valide ta présence ce soir au Volta → Niveau 5 débloqué ✨",
    progVal:     80,
    date:        'Ce Soir – 21h',
  },
  {
    id: 2,
    title:       'Club Nyx',
    subtitle:    '23h – Club Nyx – House Night',
    venue:       'Club Nyx – Paris 2ème',
    location:    'Paris 2ème',
    places:      200,
    remaining:   120,
    price:       18,
    priceLabel:  '18 €',
    xp:          100,
    tag:         "Aujourd'hui",
    badge:       null,
    hours:       '23h – 6h',
    type:        'Club',
    img:         'images/club_nyx_background.png',
    description: "Le Club Nyx accueille ce soir ses meilleurs DJs pour une House Night qui promet de faire vibrer le 2ème arrondissement. Sound system Funktion One, lumières, ambiance garantie.",
    warnMsg:     "Plus que 2 sorties pour débloquer le badge 'Noctambule'.",
    progMsg:     "Check-in ce soir → Badge Noctambule débloqué 🏆",
    progVal:     65,
    date:        'Ce Soir – 23h',
  },
  {
    id: 3,
    title:       'Open Mic – La Boîte',
    subtitle:    '20h – La Boîte, Rue des Abbesses',
    venue:       'La Boîte – Paris 18ème',
    location:    'Paris 18ème',
    places:      80,
    remaining:   45,
    price:       0,
    priceLabel:  'Gratuit',
    xp:          80,
    tag:         "Aujourd'hui",
    badge:       null,
    hours:       '20h – 1h',
    type:        'Open Mic',
    img:         'images/open_mic_background.png',
    description: "Soirée Open Mic dans l'atmosphère bohème de Montmartre. Artistes émergents, spoken word, slam et acoustique. Une ambiance intimiste et bienveillante dans une cave chargée d'histoire.",
    warnMsg:     "1ère fois à La Boîte ? Tu gagnes +20 XP bonus en arrivant avant 20h30 ⚡",
    progMsg:     "Check-in ce soir → Bonus découverte 🌟",
    progVal:     45,
    date:        'Ce Soir – 20h',
  },
  {
    id: 4,
    title:       'Concert Électro',
    subtitle:    '22h – Salle Pleyel',
    venue:       'Salle Pleyel – Paris 8ème',
    location:    'Paris 8ème',
    places:      500,
    remaining:   80,
    price:       25,
    priceLabel:  '25 €',
    xp:          120,
    tag:         "Aujourd'hui",
    badge:       null,
    hours:       '22h – 4h',
    type:        'Concert',
    img:         'images/electro_concert_background.png',
    description: "Une nuit électro exceptionnelle à la Salle Pleyel. Son cristallin, lasers verts, ambiance de folie. Les meilleurs DJs internationaux se succèdent pour une nuit inoubliable.",
    warnMsg:     "Seulement 80 places restantes ! Réserve vite avant que ça soit sold out.",
    progMsg:     "Check-in ce soir → XP × 2 activé 🚀",
    progVal:     84,
    date:        'Ce Soir – 22h',
  },
];

const USER = {
  name:       'Élodie Garron',
  email:      'elogarron@gmail.com',
  level:      4,
  levelName:  'Night Explorer',
  xp:         1240,
  xpNext:     1500,
  sorties:    12,
  badges:     5,
  rewards:    3,
  streak:     3,
  since:      'JANV 2028',
};

// App state
const STATE = {
  currentEvent: null,
  qty:          1,
  billet:       null,
};
